objects/Batch_Job__c.object
<CustomObject>
    <description>Contains the details of a batch job (Apex Scheduled Job).</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this batch job active or not.  Only active jobs will be available to the mass Schedule / Un-Schedule functions.  NOTE: setting to false will unschedule/abort any current jobs.</description>
        <inlineHelpText>Is this batch job active or not.  Only active jobs will be available to the mass Schedule / Un-Schedule functions.  NOTE: setting to false will unschedule/abort any current jobs.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <description>The Apex Class to be scheduled.  The class must implement Schedulable.</description>
        <inlineHelpText>The Apex Class to be scheduled.  The class must implement Schedulable.</inlineHelpText>
        <label>Apex Class</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cron_Expression__c</fullName>
        <description>Cron expression defining the schedule for this job.  Seconds Minutes Hours Day_of_month Month Day_of_week optional_year</description>
        <inlineHelpText>Seconds Minutes Hours Day_of_month Month Day_of_week optional_year.  Ex. 0 0 13 * * ? = Every day at 1pm, 0 0 20 * * ? 2010 = Every day in 2010 at 8pm, 0 0 22 ? * 6L = Last Friday of each Month at 10pm, 0 0 10 ? * MON-FRI = Mon thru Fri at 10am.</inlineHelpText>
        <label>Cron Expression</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Any errors creating or running the batch job will show up here.</description>
        <inlineHelpText>Any errors creating or running the batch job will show up here.</inlineHelpText>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Scheduled_Job_Id__c</fullName>
        <description>This field will be auto populated with the CronTrigger.Id when a batch job is scheduled.</description>
        <inlineHelpText>This field will be auto populated with the CronTrigger.Id when a batch job is scheduled.</inlineHelpText>
        <label>Scheduled Job Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>When set to &quot;Ready&quot; it will cause a scheduled job (CronTrigger) to be created and will then be set to &quot;Scheduled&quot; on success or &quot;Error&quot; if there was a failure.  Setting to &quot;Off&quot; will cause any existing scheduled jobs to be cancelled.</description>
        <inlineHelpText>When set to &quot;Ready&quot; it will cause a scheduled job (CronTrigger) to be created and will then be set to &quot;Scheduled&quot; on success or &quot;Error&quot; if there was a failure.  Setting to &quot;Off&quot; will cause any existing scheduled jobs to be cancelled.</inlineHelpText>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Batch Job</label>
    <nameField>
        <label>Batch Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BD_BatchJobHelper.cls
/**
 * @author John Ives
 * @date 4/22/16
 * @description Helper class to interact with Batch Job objects.
 */

public with sharing class BD_BatchJobHelper {


    public void beforeInsert(List<Batch_Job__c> jobs) {
        
        for( Batch_Job__c job : jobs ) {
            // Just schedule job if state is Ready
            if( job.State__c == 'Ready' ) {
                // Schedule the job
                scheduleJob( job );

            } else {
                // Not in the expected State
                String msg = 'New record inserts should always have a State of "Ready", this one was "'
                        + job.State__c + '", so did not schedule a job.';
                setErrorState( job, msg );
                job.addError( msg );
            }
        }
    }


    public void beforeUpdate(List<Batch_Job__c> newJobs, Map<Id, Batch_Job__c> oldMap) {


    }


    public void beforeDelete(List<Batch_Job__c> jobs) {


    }


    private Schedulable getObject( String name ) {
        Type t = Type.forName( name );
        return (Schedulable) t.newInstance();
    }


    private void setErrorState( Batch_Job__c job, String msg ) {
        job.Error_Message__c = msg;
        job.State__c = 'Error';
        System.debug( 'Changed Batch Job state to Error :: ' + msg );
    }


    private void scheduleJob( Batch_Job__c job ) {

        // Only create job if record is active
        if( job.Active__c ) {

            try {
                // Schedule the job
                Id jobId = System.schedule( job.Name, job.Cron_Expression__c, getObject( job.Apex_Class__c ) );

                // Updated fields for succesful scheduling
                job.Scheduled_Job_Id__c = jobId;
                job.State__c = 'Scheduled';

                // Clear any previous error messages
                job.Error_Message__c = '';

            } catch( Exception e ) {
                System.debug( 'Exception caught when creating a scheduled job for args ("'
                        + job.Name + '", "' + job.Cron_Expression__c + '", "' + job.Apex_Class__c + '") :: ' + e );
                throw e;
            }
        }
    }


    private void abortJob( Batch_Job__c job ) {
        // TODO make it so
    }

}