objects/Batch_Job__c.object
<CustomObject>
    <description>Contains the details of a batch job (Apex Scheduled Job).</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this batch job active or not.  Only active jobs will be available to the mass Schedule / Un-Schedule functions.  NOTE: setting to false will unschedule/abort any current jobs.</description>
        <inlineHelpText>Is this batch job active or not.  Only active jobs will be available to the mass Schedule / Un-Schedule functions.  NOTE: setting to false will unschedule/abort any current jobs.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <description>The Apex Class to be scheduled.  The class must implement Schedulable.</description>
        <inlineHelpText>The Apex Class to be scheduled.  The class must implement Schedulable.</inlineHelpText>
        <label>Apex Class</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Provide any relevant comments for this batch job.</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cron_Expression__c</fullName>
        <description>Cron expression defining the schedule for this job.  Seconds Minutes Hours Day_of_month Month Day_of_week optional_year</description>
        <inlineHelpText>Seconds Minutes Hours Day_of_month Month Day_of_week optional_year.  Ex. 0 0 13 * * ? = Every day at 1pm, 0 0 20 * * ? 2010 = Every day in 2010 at 8pm, 0 0 22 ? * 6L = Last Friday of each Month at 10pm, 0 0 10 ? * MON-FRI = Mon thru Fri at 10am.</inlineHelpText>
        <label>Cron Expression</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Any errors creating or running the batch job will show up here.</description>
        <inlineHelpText>Any errors creating or running the batch job will show up here.</inlineHelpText>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Scheduled_Job_Id__c</fullName>
        <description>This field will be auto populated with the CronTrigger.Id when a batch job is scheduled.</description>
        <inlineHelpText>This field will be auto populated with the CronTrigger.Id when a batch job is scheduled.</inlineHelpText>
        <label>Scheduled Job Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>When set to &quot;Ready&quot; it will cause a scheduled job (CronTrigger) to be created and will then be set to &quot;Scheduled&quot; on success or &quot;Error&quot; if there was a failure.  Setting to &quot;Off&quot; will cause any existing scheduled jobs to be cancelled.</description>
        <inlineHelpText>When set to &quot;Ready&quot; it will cause a scheduled job (CronTrigger) to be created and will then be set to &quot;Scheduled&quot; on success or &quot;Error&quot; if there was a failure.  Setting to &quot;Off&quot; will cause any existing scheduled jobs to be cancelled.</inlineHelpText>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Batch Job</label>
    <nameField>
        <label>Batch Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestClass.cls
public class TestClass {



	public void test() {

//		String jobId = '08e36000004W51kAAC';
//		CronTrigger ct = [SELECT TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobID];
//		String oldState = ct.State;
//		ct.State = 'COMPLETE';

		//CronJobDetail ctd = [SELECT Id, Name, JobType FROM CronJobDetail WHERE Id = :job.CronJobDetail.Id];

//		Map<Id, CronTrigger> cronTriggerMap = new Map<Id, CronTrigger>( [SELECT Id, State, CronExpression, CronJobDetail.Name FROM CronTrigger] );
//		List<Batch_Job__c> batchJobs = [SELECT Id, Name, Cron_Expression__c, Apex_Class__c, Active__c, State__c, Scheduled_Job_Id__c, Comments__c, Error_Message__c FROM Batch_Job__c ];
//
//		for( Batch_Job__c job :  batchJobs ) {
//			CronTrigger ct = cronTriggerMap.get( job.Scheduled_Job_Id__c );
//			System.debug( '\n\n>>>>>>>>>>BatchJob: ' + job + '\n>>>>>>>>>>CronTriger: ' + ct );
//		}


		//System.debug('This is a test!');
	}

}